# Generated by Django 4.2 on 2023-04-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Active', models.BooleanField(blank=True, default=True, null=True)),
                ('Deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassCode', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('HasSections', models.BooleanField(blank=True, default=False, null=True)),
                ('Active', models.BooleanField(blank=True, default=True, null=True)),
                ('Deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MasterCode', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Description', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('Active', models.BooleanField(blank=True, default=True, null=True)),
                ('Deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacultyCode', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('FirstName', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('MiddleName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('LastName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('EmailId', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Mobile', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Whatsapp', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Gender', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('DateOfBirth', models.DateField(blank=True, default=None, null=True)),
                ('JoiningDate', models.DateField(blank=True, default=None, null=True)),
                ('Salary', models.DateField(blank=True, default=None, null=True)),
                ('Photo', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Status', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('AadharNo', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Education', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('NameInBank', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('BankAccountNo', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('IFSC', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('BankCode', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Active', models.BooleanField(blank=True, default=True, null=True)),
                ('Deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SectionTitle', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('RoomNo', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Active', models.BooleanField(blank=True, default=True, null=True)),
                ('Deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StaffCode', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('FirstName', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('MiddleName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('LastName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('EmailId', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Mobile', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Whatsapp', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Gender', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('DateOfBirth', models.DateField(blank=True, default=None, null=True)),
                ('Photo', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Status', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('AadharNo', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Active', models.BooleanField(blank=True, default=True, null=True)),
                ('Deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusCode', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('Title', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('Color', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Active', models.BooleanField(blank=True, default=True, null=True)),
                ('Deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentCode', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('FirstName', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('MiddleName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('LastName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('EmailId', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Mobile', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Whatsapp', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Gender', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('DateOfBirth', models.DateField(blank=True, default=None, null=True)),
                ('FatherName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('MotherName', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Photo', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('FatherPhoto', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('MotherPhoto', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Status', models.CharField(blank=True, default=None, max_length=1, null=True)),
                ('AadharNo', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Active', models.BooleanField(blank=True, default=True, null=True)),
                ('Deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
