# Generated by Django 4.2 on 2023-04-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Password', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('EmployeeCode', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('Blocked', models.BooleanField(blank=True, default=False, null=True)),
                ('Deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
