# Generated by Django 4.2 on 2023-07-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20230719_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='MemberPrefix',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
