# Generated by Django 4.2 on 2023-07-24 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_company_memberprefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarymember',
            name='MonthlyFee',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
