# Generated by Django 4.2 on 2023-08-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_librarymember_monthlyfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeuser',
            name='Status',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
