# Generated by Django 4.2 on 2023-04-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_faculty_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmaster',
            name='Type',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
