# Generated by Django 4.2 on 2023-04-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_statusmaster_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='ClassId',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
