# Generated by Django 4.2 on 2023-04-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_section_classid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='SectionTitle',
            new_name='Title',
        ),
    ]
