# Generated by Django 4.2 on 2023-04-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_sectiontitle_section_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Active', models.BooleanField(blank=True, default=True, null=True)),
                ('Deleted', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
