# Generated by Django 4.2 on 2023-04-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultySubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacultyCode', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('SubjectId', models.CharField(blank=True, default=None, max_length=5, null=True)),
            ],
        ),
    ]
