# Generated by Django 4.2 on 2023-04-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_facultysubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='Class',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
