# Generated by Django 4.2 on 2023-04-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_staff_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='Class',
        ),
        migrations.AddField(
            model_name='student',
            name='Class',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
