# Generated by Django 4.2 on 2023-04-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_staff_class_student_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentCode', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('DocumentDate', models.DateField(blank=True, default=None, null=True)),
                ('Amount', models.FloatField(blank=True, default=None, null=True)),
                ('Discount', models.FloatField(blank=True, default=None, null=True)),
                ('Fine', models.FloatField(blank=True, default=None, null=True)),
                ('TotalAmount', models.FloatField(blank=True, default=None, null=True)),
                ('Type', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('Mode', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
