# Generated by Django 4.2 on 2023-04-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_paymentmode'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
