# Generated by Django 4.2 on 2023-04-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_feetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='TypeCode',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='paymentmode',
            name='ModeCode',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
