# Generated by Django 4.2 on 2023-04-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_feetype_typecode_paymentmode_modecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feetype',
            name='TypeCode',
        ),
        migrations.RemoveField(
            model_name='paymentmode',
            name='ModeCode',
        ),
    ]
