# Generated by Django 4.2 on 2023-04-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_feetype_typecode_remove_paymentmode_modecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='MonthYear',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
    ]
