# Generated by Django 4.2 on 2023-04-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_fee_monthyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='MonthYear',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
