# Generated by Django 4.2 on 2023-04-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_fee_monthyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='ClassTeacher',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
