# Generated by Django 4.2 on 2023-04-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_fee_documentcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Section',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
