# Generated by Django 4.2 on 2023-04-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_student_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='Remarks',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
