# Generated by Django 4.2 on 2023-04-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_fee_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='ReferenceNo',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
