# Generated by Django 4.2 on 2023-04-13 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_fee_referenceno'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='ClassFee',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
