# Generated by Django 4.2 on 2023-04-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_section_classteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExpenseCode', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('DocumentDate', models.DateField(blank=True, default=None, null=True)),
                ('Amount', models.FloatField(blank=True, default=None, null=True)),
                ('DocumentNo', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('InvoiceCopy', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Type', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Remarks', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('Deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
