# Generated by Django 4.2 on 2023-04-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_expense_expensetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='Mode',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
