# Generated by Django 4.2 on 2023-04-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_expense_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='ReferenceNo',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
