# Generated by Django 4.2 on 2023-04-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_expense_referenceno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassId', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('SectionId', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('SubjectId', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('FacultyId', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('Day', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('CreatedBy', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('Deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
