# Generated by Django 4.2 on 2023-04-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='EndTime',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='StartTime',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
