# Generated by Django 4.2 on 2023-04-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_routine_endtime_routine_starttime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('StartDate', models.DateField(blank=True, default=None, null=True)),
                ('EndDate', models.DateField(blank=True, default=None, null=True)),
                ('Remarks', models.CharField(blank=True, default=None, max_length=500, null=True)),
                ('Deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
