# Generated by Django 4.2 on 2023-04-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_exam'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubjectId', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('ExamId', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('ClassId', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('SectionId', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('PaperDate', models.DateField(blank=True, default=None, null=True)),
                ('Content', models.TextField(blank=True, default=None, null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='CreatedBy',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='CreatedDate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
