# Generated by Django 4.2 on 2023-04-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_exampaper_exam_createdby_exam_createddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
