# Generated by Django 4.2 on 2023-04-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_exam_createddate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentCode', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('ClassId', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('SectionId', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('ExamId', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('SubjectId', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('PaperId', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('Marks', models.FloatField(blank=True, default=None, null=True)),
                ('Deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
