# Generated by Django 4.2 on 2023-04-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_reportcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Active', models.BooleanField(default=False)),
                ('Deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
