# Generated by Django 4.2 on 2023-04-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_schoolsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassId', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('SubjectId', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('FacultyId', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('SessionId', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('Deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
