# Generated by Django 4.2 on 2023-04-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_subjectclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='FullName',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='FullName',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='FullName',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
