# Generated by Django 4.2 on 2023-04-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_faculty_fullname_staff_fullname_student_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='SessionId',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='exampaper',
            name='SessionId',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='SessionId',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fee',
            name='SessionId',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='routine',
            name='SessionId',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
