# Generated by Django 4.2 on 2023-04-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_exam_sessionid_exampaper_sessionid_expense_sessionid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='RollNumber',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
