# Generated by Django 4.2 on 2023-04-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_student_rollnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='exampaper',
            name='TotalMarks',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
