# Generated by Django 4.2 on 2023-04-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_exampaper_sectionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PageCode', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('Title', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('Visible', models.BooleanField(default=False)),
            ],
        ),
    ]
