# Generated by Django 4.2 on 2023-04-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='PageUrl',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
