# Generated by Django 4.2 on 2023-04-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_menu_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='SortOrder',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
