# Generated by Django 4.2 on 2023-04-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_menu_sortorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassId', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('SectionId', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('Completed', models.BooleanField(default=False)),
                ('CompletedOn', models.DateField(blank=True, default=None, null=True)),
                ('Deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='class',
            name='HasSections',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Visible',
            field=models.BooleanField(default=True),
        ),
    ]
