# Generated by Django 4.2 on 2023-04-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_syllabus_alter_class_hassections_alter_menu_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='ChapterNo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='SubjectId',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='Title',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
