# Generated by Django 4.2 on 2023-04-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_syllabus_chapterno_syllabus_subjectid_syllabus_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentCode', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('AttendanceDate', models.DateField(blank=True, default=None, null=True)),
                ('MarkedBy', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
    ]
