# Generated by Django 4.2 on 2023-04-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='Status',
            field=models.CharField(blank=True, default=None, max_length=2, null=True),
        ),
    ]
