# Generated by Django 4.2 on 2023-04-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='SessionId',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
